#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tests for the grounded_claim_ids primitive (verified + grounded, by claim_id).

Real store + files (no mocks): register a source, record a run reading it ->
output, claim on the output with a claim_id, verify. The primitive returns the
claim_id iff the claim is verified AND grounded (chain reaches the registered
source). Each test writes into its own PostgreSQL schema (tests/conftest.py).
"""

import scitex_clew as clew
from scitex_clew._grounded import grounded_claim_ids
from scitex_clew._sources._writer import register_source


def test_returns_verified_and_grounded_claim_id(tmp_path):
    # Arrange
    manifest = tmp_path / ".scitex" / "clew" / "sources.json"
    src = tmp_path / "data.csv"
    src.write_text("x\n1\n")
    out = tmp_path / "out.json"
    out.write_text('{"n": 1}\n')
    register_source([src], sources_path=manifest, root=tmp_path)
    with clew.session() as run:
        run.record_input(src)
        run.record_output(out)
    clew.add_claim("paper.tex", "value", 1, "1", source_file=str(out), claim_id="q1")
    clew.verify_all_claims()
    # Act
    result = grounded_claim_ids(workdir=tmp_path)
    # Assert
    assert result == ["q1"]


def test_excludes_ungrounded_claim(tmp_path):
    # Arrange — gate active via a registered file, but the run reads an
    # UNregistered file, so the claim's chain reaches no registered root.
    manifest = tmp_path / ".scitex" / "clew" / "sources.json"
    registered = tmp_path / "registered.csv"
    registered.write_text("a\n1\n")
    other = tmp_path / "other.csv"
    other.write_text("b\n2\n")
    out = tmp_path / "out.json"
    out.write_text("{}\n")
    register_source([registered], sources_path=manifest, root=tmp_path)
    with clew.session() as run:
        run.record_input(other)
        run.record_output(out)
    clew.add_claim("paper.tex", "value", 1, "1", source_file=str(out), claim_id="q2")
    clew.verify_all_claims()
    # Act
    result = grounded_claim_ids(workdir=tmp_path)
    # Assert
    assert result == []


def test_grounded_claim_with_autogenerated_id_is_returned(tmp_path):
    # Arrange — grounded claim, no EXPLICIT claim_id (add_claim auto-generates one).
    manifest = tmp_path / ".scitex" / "clew" / "sources.json"
    src = tmp_path / "data.csv"
    src.write_text("x\n1\n")
    out = tmp_path / "out.json"
    out.write_text("{}\n")
    register_source([src], sources_path=manifest, root=tmp_path)
    with clew.session() as run:
        run.record_input(src)
        run.record_output(out)
    clew.add_claim("paper.tex", "value", 1, "1", source_file=str(out))
    clew.verify_all_claims()
    # Act
    result = grounded_claim_ids(workdir=tmp_path)
    # Assert — every claim has a claim_id (auto-generated when none given), so the
    # grounded claim is returned by its stored id (user-provided or auto).
    assert len(result) == 1
