"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil
from pathlib import Path

import pytest

if shutil.which("scitex-dev") is None:
    pytest.skip(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]",
        allow_module_level=True,
    )


def test_audit_all_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act — anchor on this file so the gate grades the checkout under
    # test, never an installed copy or somebody else's tree.
    result = audit_all_for_package(
        "scitex-clew",
        path=Path(__file__).resolve().parents[2],
    )

    # Assert — the gate returns None on success and raises on violation.
    assert result is None
